services:
  backend:
    build: ./src
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - LLM_API=${LLM_API}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - TWELVE_DATA_API_KEY=${TWELVE_DATA_API_KEY}

  frontend:
    build: 
      context: ./frontend
      args:
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}

networks:
  app-network:
    driver: bridge
