import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ModeToggle } from "@/components/theme/mode-toggle";
import { ThemeProvider } from "@/components/theme/theme-provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <div className="min-h-screen flex flex-col bg-gradient-to-b from-white via-blue-50 to-blue-100 dark:from-gray-900 dark:via-gray-950 dark:to-gray-900 transition-colors">
                        <header className="sticky top-0 z-30 flex items-center justify-between px-10 py-5 bg-white/80 dark:bg-gray-900/80 shadow-md backdrop-blur-md rounded-b-2xl border-b border-blue-100 dark:border-gray-800">
                            <div className="flex items-center gap-4">
                                <span className="flex items-center text-3xl font-extrabold text-blue-700 dark:text-blue-400 tracking-tight">
                                    <svg
                                        className="w-9 h-9 mr-2 text-blue-500 dark:text-blue-400"
                                        fill="none"
                                        stroke="currentColor"
                                        strokeWidth={2}
                                        viewBox="0 0 24 24"
                                    >
                                        <path
                                            strokeLinecap="round"
                                            strokeLinejoin="round"
                                            d="M3 17l6-6 4 4 8-8"
                                        />
                                    </svg>
                                    Market<span className="text-blue-400 dark:text-blue-300">Pulse</span>
                                </span>
                            </div>
                            <ModeToggle />
                        </header>
                        <main className="flex-1 w-full max-w-5xl mx-auto px-6 py-8">
                            {children}
                        </main>
                        <footer className="flex flex-col items-center justify-center p-5 bg-white/80 dark:bg-gray-900/80 shadow-inner rounded-t-2xl border-t border-blue-100 dark:border-gray-800 mt-8">
                            <p className="text-sm text-gray-700 dark:text-gray-400">
                                © {new Date().getFullYear()} <span className="font-semibold">Market-Pulse</span>. All rights reserved.
                            </p>
                            <a
                                href="https://rahulab.vercel.app"
                                target="_blank"
                                rel="noopener noreferrer"
                                className="mt-1 text-xs text-blue-700 dark:text-blue-400 hover:underline transition-colors"
                            >
                                Visit my portfolio
                            </a>
                        </footer>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
